apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-fantasy-football-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-fantasy-football-service
  template:
    metadata:
      labels:
        app: mysql-fantasy-football-service
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-persistent-storage
      containers:
        - name: mysql-fantasy-football-service
          image: mysql/mysql-server:8.0
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ""
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_DATABASE
              value: "fantasy-football-service"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql # Mount the persistent volume to the MySQL data directory
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-fantasy-football-service-service
spec:
  type: ClusterIP
  selector:
    app: mysql-fantasy-football-service
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the size as needed
