apiVersion: apps/v1
kind: Deployment
metadata:
  name: fantasy-football-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fantasy-football-service
  template:
    metadata:
      labels:
        app: fantasy-football-service
    spec:
      containers:
      - name: fantasy-football-service
        image: sail-8.3/app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000