apiVersion: apps/v1
kind: Deployment
metadata:
  name: fantasy-football-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fantasy-football-service
  template:
    metadata:
      labels:
        app: fantasy-football-service
    spec:
      containers:
        - name: fantasy-football-service
          image: ghcr.io/markvdkort/s6-fantasyfootballservice:development
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: github-registry-login
